### PR TITLE
Added edit button to ListItem

### PR DESCRIPTION
**Pull request by gmisail**
I included the library "react-icons" (https://react-icons.github.io/) and created a button that is aligned to the right of each ListItem object. For now, the callback just prints which button is pressed, but it can be rigged up to open an 'Edit' modal or something. Also, I removed the edit button from the List route, since I thought it would be redundant if each item had an edit button.

### CODE REVIEW

**Comment by gmisail** [comment]
If everything looks alright on your end I can merge, or if you want to make some edits please feel free.

**Comment by metzlr** [comment]
Looks good. Although I don't know why you added the "align-self-start/end." modifiers to the divs and removed the "align-items-center" modifier from the flex container. I'm pretty sure everything should be aligned to the center on the y-axis?

**Review by metzlr — COMMENTED** [review]
There I removed them

**Comment by metzlr** [comment]
Also removed the mr-auto class since it isn't necessary with the justify-content-between modifier I had

**Comment by gmisail** [comment]
Will this still work even though there are 3 objects (text, claim button, and edit button)? I could be thinking of something else, but won't there be an equal amount of space between each object? I was thinking that the text would be left aligned, with the buttons being right aligned.

**Comment by metzlr** [comment]
Yeah you're that's what justify-content-between does. And it would be like that if they were all in the same div, but if you put the the claim and edit button in a div together it will just put space between that div and the text which is how it is now. But you could also just do mr-auto on the text like you had.

Oh I see what you mean with those. But "align-..." modifies the cross axis placement for flex objects. So if its a flex row (which it is) that modifies the y-axis. "justify-..." modifies the x-axis.

**Comment by gmisail** [comment]
Ah okay, I see what you're saying.

**Comment by gmisail** [comment]
I'm on my phone right now so I can't really test it out, but if everything is good you can merge and I'll take your word for it

**Pull request merged**
