### PR TITLE
Update styles and layout

### PR DESCRIPTION
**Pull request by gmisail**
I made some relatively minor improvements to make the user interface (at least in my opinion) a little nicer to look at. First of all, I embedded the editor within a Bootstrap card, so that it matches the look of the list. This helps make the interface look more predictable and cohesive as opposed to having a standalone canvas. On the other hand, I removed the `List Items` text since I figured that it wasn't necessarily needed. I also changed the background color of the canvas to white, but I think a light gray could work well too. Ultimately I made these changes so that the overall interface would look less cluttered. I personally think it looks good (I'm kinda a sucker for the card-based web design) but I can see how it could look _too_ minimal.

Screenshot_2020-10-31 React App

### CODE REVIEW

**Comment by gmisail** [comment]
Also apparently my commits from #28 showed up in this branch as well, but they shouldn't cause any conflicts.

**Comment by metzlr** [comment]
I definitely like the minimalist look but its also definitely feels pretty blank. Although I think that's more because its still pretty basic. It also might look better if in the future we switched it to a dark theme but I don't know.

I do think that the "Add" button should always be at the top of the list though. If you end up having a lot of items, you would have to scroll all the way down to hit it, which would be especially annoying on mobile. This could be sorta solved if we put the item list in a scroll view so that the button never moves, only the items do. But I think its just easier to leave it at the top.

It would actually be pretty cool to have the editor take up the entire left 2/3rdsish of the screen, from top to bottom (excluding the navbar), and then adding panning/zooming to it as well, sort like the way google maps does it, to make it feel more interactive.

**Comment by gmisail** [comment]
We could probably add light / dark mode, since that's all the rage these days. At least for the current color scheme, by keeping the card-style approach we could make the background (excluding the cars themselves) a light gray to distinguish themselves from the background. This will hopefully create some depth. Maybe a light box shadow would help in that regard as well..?

As for the add button, I personally think it looks better at the bottom I agree with you in terms of functionality. Maybe instead of the text we could replace it with a "+" icon or something.

**Comment by gmisail** [comment]
I revised my original design to have a light gray background and a slight drop shadow on the editor and list elements. I feel like this makes it feel a little less empty but of course we are not bound to this design.

Screenshot_2020-11-02 React App

**Pull request merged**
