### PR TITLE
Dockerizing

### PR DESCRIPTION
**Pull request by metzlr**
Alright so I looked into Docker and I think I managed to set up a decent development and production configuration.

First, I reordered the repository structure to be separated into distinct parts. I created two different docker-compose configs: docker-compmose.dev.yml for the dev environment and docker-compose.yml for the production environment. And then I put Dockerfiles in each of the relevant parts of the app. The frontend needed separate Dockerfiles for development/production, so the dev one has the .dev suffix.

Here's a basic rundown of the configs:

The development environment has 3 containers: frontend, server, and db. The frontend basically just runs the built in create-react-app dev server (and is configured to support hot reloading). The server just runs the echo server, and finally the db runs the rethinkdb server (storing data files in the project root of the host machine under "rethinkdb_data"). 

The production environment is a bit more complex. For the frontend, the docker container first builds the react files, then uses a package called serve to serve them (a method that's recommended in the create-react-app docs). The server and db are basically the same, but then there's an additional container called proxy that runs nginx and routes requests to either the frontend or server containers based on the URL ("/" goes to frontend and anything that begins with "/api/" goes to server).

I put instructions for running both environments in the README.

I also added some code that creates the initial "dd_data" database and "rooms" table if they don't exist, so we don't have to do that manually anymore.

Overall I think this makes everything much cleaner, and there's probably lots of ways it can still be improved. The only slightly annoying thing at the moment is that when changing Golang code, you have to restart the entire environment (re-run docker compose). And since it detects changes, it rebuilds the server docker image, which reinstalls all of the Go packages. All in all it takes about 15 seconds total to start up the environment again after changing something. Not too bad, but I think there's probably ways to either support hot-reloading for Golang code or at least prevent it from reinstalling packages after every change.

### CODE REVIEW

**Comment by gmisail** [comment]
I'll try this out in a second, but my only confusion is with the serve library, since won't the frontend be served by the server anyways? I'm pretty sure it's configured to host it, at least.

**Comment by metzlr** [comment]
I removed the code that would serve the frontend from the backend server. Now the backend will just serve as the API/socket stuff. We could serve the files from the backend server, but then the frontend wouldn't have its own docker container in deployment. The backend container would then have to pull in the frontend files and build them. Not a huge deal, but it just seemed like its better to separate each part into its own container.

**Comment by metzlr** [comment]
I tweaked the development setup a bit to make it more like the production one. Now it also uses a nginx proxy server that handles all incoming requests, so the entire site is served under a single port (5500 at the moment). 

Also removed some ports that didn't need to be exposed.

**Comment by gmisail** [comment]
I'll take a look at it now, Docker was pretty difficult to setup on my Linux machine for whatever reason.

**Comment by gmisail** [comment]
Everything seems to work well for me. I also added a little blurb of code that will create a templates table, similar to what we had for the rooms table.

**Comment by metzlr** [comment]
Looks good

**Pull request merged**
