### PR TITLE
Delete rooms

### PR DESCRIPTION
**Pull request by gmisail**
This PR adds functionality for deleting rooms from the settings menu. Once you click on settings and scroll down, you should see a red button. Clicking this button will delete the room and refresh the window for every client. These changes will also be reflected in the room history panel on the home page.

To improve the user experience, maybe instead of refreshing the page it could redirect to the home page? Also, asking if they meant to delete the page would be nice.

### CODE REVIEW

**Comment by metzlr** [comment]
I think that clicking the same button twice is still a bit too easy, so I changed it so that when you first click delete, a confirm button appears that you need to click. 

This still might be too easy tbh so in the future it might be good to add an input that appears where the user needs to type the name of the room before being able to confirm the delete (like how GitHub does it with repositories). I started doing this (added the match checking functionality to SingleInputForm) but stopped because of an annoying styling issue with bootstrap. The form focus outline is blue which looks weird with the red delete button and there's no simple, clean way to change that to use our custom red color afaik. For now I think what we have is fine unless you want to take a stab at it. 

I also added a new custom outline button style and changed the delete button to that style, which I think looks cleaner.

Finally, I moved the line that removes the room from the local history to the delete response callback, so it isn't executed if the delete event fails on the server for some reason, and I also added a line that redirects the user who deleted the room to the homepage.

Screenshot from 2021-06-03 14-16-19
Screenshot from 2021-06-03 14-16-36

**Comment by gmisail** [comment]
I can take a look at doing the Github-style confirmation that you suggested, I was thinking about that as well but wasn't sure if it was *really* necessary. I can take another look at it and try to address those styling issues, but I like what we have at the moment so its not too high up on the priority list.

**Comment by gmisail** [comment]
Fixed issue where browsers would not redirect on deletion. I moved the redirect line to the socket connection so that it'll redirect when it receives a response instead. I'm going to do a little more testing before merging but I think everything is okay feature-wise.

**Comment by metzlr** [comment]
I didn't put the redirect in the response since I thought that it might be better if it didn't redirect anyone else connected to the room who didn't click the delete button, since otherwise it would just put them back to the home screen, remove the room from the history and they might not have any idea what happened.

But honestly just showing the "Connection failed screen" or whatever instead isn't any better, so it's fine the way you have it.

In the future it might be good to show a "Room has been deleted" message or something when a user tried to access a deleted room.

**Comment by gmisail** [comment]
I understand why it would make sense to show the 'disconnected' screen, but also I feel like having a room deleted page or whatever would be included in a more robust error system on the client (I think there is a TODO for that in one of the files..?) Either way, I think they're both gonna have some ambiguity until a better system is implemented. The only reason I feel like this one makes more "sense" is because you have that visual feedback of your room being deleted as opposed to seeing an error screen, since there *technically* isn't an error. Again, both ways don't make a lot of sense to the user without that more robust error system.

**Comment by gmisail** [comment]
I think this feature is fine for now (I can't find any issues and some of the problems that we had will be addressed with the improved error system) so I'll merge into main.

**Pull request merged**
