### PR TITLE
Port backend to Node.js

### PR DESCRIPTION
**Pull request by gmisail**
So far I have added the room-based web socket system. A lot of the logic carried over from Go, but there are a couple differences of note. First of all, I made it so that the system is based off of EventEmitter; when an event is received, the event will be emitted with the given `event`. The data that was sent to the server (along with the socket's id) will be send to the specified callback. This system is much easier to maintain and modify, since we do not need to deal with casting hell and unmarshalled JSON objects. There also is not a Client object like in the previous implementation. Instead, there is a `connections` map where the socket for a given `id` can be looked up. 

For debugging, the console will output every socket id that is in each room when it is "pinged". This can be useful for making sure that room's are being deleted / added correctly. 

Also, I added `chalk` to make the console look pretty.

### CODE REVIEW

**Comment by gmisail** [comment]
Since this is not close to being complete (currently the Express project is alongside the Go project) I added a quick HTML file that will interact with the server. Not very useful, but it has the ability to send and receive messages and events.

**Comment by gmisail** [comment]
The new backend should be ready for deployment, barring any bugs or issues that I may have missed.

**Comment by gmisail** [comment]
Okay, all of the merge conflicts should be resolved now.

**Comment by gmisail** [comment]
I setup Husky so that it will run prettier in both the frontend and server by setting up a parent NPM project that has the devDependencies that apply to both the frontend and server.

*Note:* You may need to delete the `node_modules` and `package-lock.json` from the frontend and run `npm install`, apparently there was an issue with the parent project but it ended up working fine.

**Comment by metzlr** [comment]
I removed the 'sendResponse' field from the data that's actually sent back to the client (since its not needed).

Other than that I think things look good

**Comment by gmisail** [comment]
Merging, but I think we should keep an eye out for any issues during user testing since I almost ensure that I missed something.

**Pull request merged**
