### PR TITLE
Changed frontend proxy from localhost to 'proxy' network

### PR DESCRIPTION
**Pull request by metzlr**

### CODE REVIEW

**Comment by gmisail** [comment]
Issue is still occurring with this change unfortunately.

**Comment by metzlr** [comment]
Alright so I figured out what was the issue. The problem was that the URL used when creating the WebSocket object in the frontend code was hardcoded (aka it wasn't using the React proxy). 

I tried a bunch of different things to try and get it to use the Proxy (including setting up a "setupProxy.js" file as talked about [here](https://create-react-app.dev/docs/proxying-api-requests-in-development/)) but nothing worked.

So I just changed it to grab the host name that's stored in local storage. I'm not sure if this is a bad way to do it or not but it definitely works (I tested it on my own DO droplet).

I also reverted back the first change I made (which I think works, but is just not necessary).

**Comment by gmisail** [comment]
I don't really see why it would be an issue considering it just grabs the current URL, sure it isn't elegant but it works for now. I'll test this and then get back to you if there are any issues.

**Comment by gmisail** [comment]
Everything works as expected.

**Pull request merged**
