### PR TITLE
Room editor complex shapes 

### PR DESCRIPTION
**Pull request by metzlr**
Adds support for more complex room shapes . Also adds a second canvas to serve as a background layer. Moved the grid to this new background layer.

### CODE REVIEW

**Comment by gmisail** [comment]
The rooms themselves look really good. The collisions are really inconsistent, but I am not sure if you implemented it or if its a browser thing. One possibility would be to look into SAT collisions maybe, depending on how you implemented it. This library here (https://github.com/jriecken/sat-js) looks pretty good, but again depending on the implementation of the room renderer it might be tougher to integrate a library as opposed to writing a custom collision system.

**Comment by metzlr** [comment]
Yeah I didn't add any additional collision detection yet. Right now it just won't let you move objects outside of the max/min x and y of the room object itself. And honestly I'm not sure if having any additional collision detection would even be necessary. It might just make it more annoying when someone is trying to arrange lots of things in the room, especially with objects that might be a tight fit. Also 

Although I guess it could be cool it to have it but instead of actually blocking object movement, it just highlights the object red or something when its out of bounds, so I do think I'll try and add it.

**Comment by gmisail** [comment]
Well I was referring more to the boundaries of the room, like having a polygonal collision shape that collides with the objects within the room. Not strictly required, but it may be more efficient (not 100% on that tho)

**Comment by metzlr** [comment]
Yeah I was meaning the boundary collisions. I don't think its a huge deal if the objects can be moved outside the boundaries, but like I said it might be cool to still have some sort of visual indication when they aren't in the room.

**Comment by metzlr** [comment]
Alright I added collision detection to the boundaries. Now whenever you move an item out of bounds it turns red.

**Comment by gmisail** [comment]
I actually like how the red looks as opposed to having a collision.

**Pull request merged**
