### PR TITLE
Editor tools

### PR DESCRIPTION
**Pull request by metzlr**
Adds a toolbar to the editor. Currently only has 3 buttons, which are enabled when an object is selected. The rotation button and lock button (which prevents the item from being able to be moved and disables the other toolbar buttons when enabled) are functional, at least on the client side. The 'X' button (which I was thinking would be used as a shortcut to hide an item from the editor), isn't yet. 

Some of the socket events and the item model will definitely need to be edited to support the new rotation and locked properties.

### CODE REVIEW

**Comment by gmisail** [comment]
I feel like `X` button would be more suitable if it was for deleting an item, as opposed to hiding it. Isn't toggling the item in the editor the same thing as hiding it? Also, I am not sure if this possible with the current implementation, but couldn't we add rotation as a property similar to `x`, `y`, `w`, and `h`? Like maybe it is represented by `r` where its the number of degrees?

**Comment by metzlr** [comment]
Yeah I meant it would basically set the visibleInEditor property to false. We could do delete as well, although I was really only thinking it would be nice since it's so annoying to have to click edit and then check the tiny checkbox to get something in the editor. In fact, now that I'm thinking about it, we should probably add that as an option to the drop down menu.

Yeah I'm assuming we would just add an editorRotation property.

**Comment by gmisail** [comment]
That is a fair point, also it may lead to accidental deletions if its too open. Also I agree, it would probably be nicer to add it to the dropdown since its not _really_ a property of the object itself when you think about it. As for the rotation, are we gonna include smaller increments of angles, like maybe 15 or 30 degrees instead of 90. I don't think this is really needed, but would there be much of a performance hit if it only increments by 90 degrees? I usually stray to the side of performance so I think we should do what you mentioned, but I guess it is something to consider.

**Comment by metzlr** [comment]
Ok so I simplified the item update events a bit. Now there are two event names "updateItem" and "updateItemInEditor". They both use the same syntax/properties and have the same handler on the backend, but the first will send back an event named "itemUpdated" and the second an event named "itemUpdatedInEditor". That way when sending/receiving updates only needed for the editor, we can just send/subscribe to that version of the event.

I also cleaned up some messy code on the frontend that handled incoming/outgoing data to the backend. Before it used a bunch of conditionals to handle the difference between an empty item property variable in JavaScript and an empty (zero) variable in Go. I realized that most of this was because I had been setting empty values as "undefined" on the frontend side, which made things way more confusing than they needed to be. So now empty fields should be "null" on the frontend and whatever the zero value is for that variable type on the backend and its a lot cleaner.

The rotation and locking should now be fully working. I added the new 'show/hide from editor' button to the itemlist menu and removed the hide button in the toolbar.

For the rotation, we could add more angles, and I think we definitely will have to if we ever add shapes other than rectangles, although right now it might make some of the border detection stuff not look quite right since the collisions use the item's bounding box. It honestly still might look fine though so I'll probably try that out real quick. 

I changed a lot of stuff with these commits so there's probably some issues

**Comment by metzlr** [comment]
Yeah collision detection with smaller rotation increments doesn't look right on corners of the room that are concave, so in order to do it we would need to add polygon collision detection.

**Comment by gmisail** [comment]
Did you set up the frontend events for synchronizing the movements? Right now, only the item properties are updating but that would make sense if the editor related stuff hasn't been integrated yet. Other than that, I like how the two buttons look as opposed to three and how the visibility was moved to the dropdown.

**Comment by gmisail** [comment]
As for the collisions, would it make sense to use something like [SAT.js](https://github.com/jriecken/sat-js) since it _should_ handle more complex polygons?

**Comment by metzlr** [comment]
Alright hopefully thing should be working now, but please try to break it.

I ended up actually changing a lot from my previous commits because I realized there were still a lot of unnecessary functions and the state management was kind of a mess. I'm sure there are still ways we can improve the way state is handled, especially between the RoomRoute and RoomCanvas, and that might even mean switching to something like Redux in the future, but this seems alright for now.

I removed the "updatedItemInEditor" variation on the "updateItem" event because as it turns out the previous performance problems with having one update handler aren't really an issue since I changed the items from being stored in a Map to an array a while back (and I tested it with a ton of items, still didn't really see any stuttering), although maybe this will be an issue in the future and we will have to separate the events again.

Now all the socket events are sent directly from the RoomRoute.

**Comment by gmisail** [comment]
I know you asked me to break things but I couldn't find any bugs really. Everything works well across clients, at least on my local network. There weren't any performance hiccups, but I am sure that will change once we are running on an actual server. I am also not against using Redux, if it would streamline the process. 

On another note, I cleared up the merge conflicts and added some icons to the "Show / Hide in Editor" dropdown button. The icons change depending on the state of the button (visible or not) but I am kinda torn on what I want the button to represent.  In a previous commit I had it so the icon would represent the current state (if the object was hidden, then the eye would be closed) but I changed it to what the state will be if you click it (if the object is hidden, it will have an open eye) I personally kinda like the way I attached below (and also the most recent commit) because the icon isn't being juxtaposed with the text, since having a closed eye next to the word "show" feels wrong for some reason. 

image
image

**Comment by metzlr** [comment]
Well I'm sure some issues will come up.

I agree, the way you have it makes the most sense. I cleaned up the dropdown menu CSS a bit more and made sure everything was using the same styling.

**Pull request merged**
