### PR TITLE
Project restructuring

### PR DESCRIPTION
**Pull request by gmisail**
I merged the two sides so that the root route is the backend, and the frontend is all within the frontend folder. Note, as of right now, you'll need to build the site before you can see changes. I'm open to a faster alternative, since building the site for every change isn't really quick. Anything will work really, as long as the server has access to the `index.html` and its related files.

### CODE REVIEW

**Comment by metzlr** [comment]
You're right that it is annoying to have to build the frontend every time. I think I found a better solution (although we can still leave the stuff you added since its something we'll have to have eventually anyways). Create-react-app allows you to add a proxy to the backend server in the package.json, so I just added that and from what I can tell it works great. So now we can just run the frontend server as normal (while also having the backend server running) and it will send requests to the backend.

**Comment by gmisail** [comment]
I'm not sure why this is occurring, but when I initially load the page everything works fine. However, when I refresh I get the JSON data: `{"message":"Not Found"}`. Can you reproduce this issue or is this just on my machine?

**Comment by metzlr** [comment]
Are you connecting to localhost:3000 while also having the backend and rethinkdb servers loaded?

**Comment by gmisail** [comment]
Ah I was connecting to `localhost:8000` instead. While we'll have to fix that at some point, I don't think it is related to this issue. Other than that everything looks good.

**Pull request merged**
