### PR TITLE
Import & export

### PR DESCRIPTION
**Pull request by gmisail**
As I mentioned previously, I replace the import-export functionality with the Room-ID based cloning system. So, instead of exporting as a file and then importing it, you can just put in a room ID and then clone. This will copy over all necessary properties and items. If it is successful, it will refresh the page. If not, then it will send an error in the console (this should be replaced later.) 

I also included the vertex editor, which is simply a grid of (x, y) coordinates that indicate the points of the room. They change dynamically just like any other property.

Let me know if there are any game-changing issues; as of right now I am aware of some rendering issues when the changing the dimensions of the room but that isn't really critical.

### CODE REVIEW

**Comment by gmisail** [comment]
Also, there are quite a few merge conflicts that I'll sort through so this PR is far from being merged.

**Comment by gmisail** [comment]
@metzlr I have run into an issue where objects cannot be deleted in the editor (once you refresh the page they're gone, so I assume they're actually being deleted.) Apparently, the items cannot be looked up by their ID's, which is interesting since all of the functions work (claim, edit, etc.) If you would like to take a look at it please do, since you know the renderer better and I have been unable to track it down as of right now. This may be an issue with the master branch as well, since it uses (pretty much) the same logic. @metzlr

**Comment by gmisail** [comment]
@metzlr Okay, I believe that all of the merge conflicts have been sorted out. Let me know if you see any issues, especially with cloning since I am sure there are corner cases that I have not accounted for. Right now, it updates the data and then refreshes all of the clients to account for the changes.

**Comment by metzlr** [comment]
Most things look good, but I made some tweaks.

- Improved VertexForm: Added an "Update" button so that changes to the layout aren't shown until its pressed. Fixed annoying thing where you couldn't have an empty field for vertex x and y inputs. Now, it won't let you submit (press "Update") if the fields aren't all filled.
- Changed button styles in to match rest of site
- Changed all of the "List..." naming schemes on the backend (e.g. ListItem, List) to "Room..." so things are more consistent
- Changed some event names/response names to match naming scheme
- Added bold "This is not reversible" text to Clone Existing Room description
- Removed unused actions from context
- Fixed some other minor issues.

Before this is merged though I think there needs to be some sort of error handling system for room cloning. Like if you put in an invalid ID the entire room just becomes unusable. I saw you had some sort of http errors on the backend, but they were commented out.

**Comment by gmisail** [comment]
Here is a screenshot of the modal changes, just for reference. 
image

**Pull request merged**
