### PR TITLE
Template viewer and some other stuff

### PR DESCRIPTION
**Pull request by metzlr**
This PR is smaller than it looks. I moved around some files on the frontend, which git counts as code additions.

General changes:
- Adds TemplateRoute. It's basically the same as RoomRoute but nothing is editable (since you're viewing the template).
- Reorganized context reducers
    - RoomRoute and TemplateRoute both use the same state in the redux store (since there's a lot of overlap in their state), but separate reducers/actions
- Changed thumbnails in the template gallery to now redirect to the template's corresponding TemplateRoute when a clicked
- Added more obvious link the template gallery to the home page
- Moved around some components in frontend project directory
    - Components that are route-specific (like RoomEditor) are now stored under their respective routes
    - Components that are basically sub-components of other components (like ListItem) are now stored under their parent component
- Organized the Joi validation schemas on the backend
- Improved item duplication (now duplicate items are slightly offset from original item)
- Fixed frontend bug where item updates were causing some fields to be incorrectly set to undefined
- Room bounds are now rendered in front of items while being edited
- Updated react-icons to newer version
- Added new ClipboardLink component (currently used in the "Share" modal in the room & template routes) that displays a link with a button to copy it to clipboard

I think the way we previously had room links and IDs mentioned across the site is a bit confusing (even though we as developers know that they are kind of interchangeable). Therefore, I changed it so we basically just mention the links as the way to share a room/template across the site, which I think is much cleaner. Obviously a user could still record the ID itself if they want to, but there's really no reason to do that. Links are just more intuitive
- Removed mention of template & room ID from share modal and create room modal
- Removed Room ID input from join room modal on homepage. Now the modal just tells the user that they need the link to a room in order to edit it

### CODE REVIEW

**Comment by gmisail** [comment]
Everything looks good, however I feel like the template button should be styled as well. It just seems out of place as a link in my opinion.

**Comment by metzlr** [comment]
Ok a lot of changes here. Mostly styling stuff
- Reworked styling on lots of pages (especially homepage)
- Reworked StorageController room history to properly keep track of recently accessed rooms and wrote some unit tests to better verify that everything works
- Can now favorite recent rooms
- Added DropdownMenu component (basically just a reusable version of the dropdown menu previously used for ListItems)
- Unified thumbnails on homepage and template gallery into a reusable RoomThumbnail component
- Added RoomThumbnailGrid component (can be used to display RoomThumbnails in a grid)
- Replaced canvas grid background with an SVG and created an easy-to-use GridBackground component
- Added grid background to template gallery page
- Fixed some issues with the favicon

**Comment by gmisail** [comment]
User interface looks great, my only question is do we really need the "clone from id" field in the room settings? Aside from extracting the ID from the URL, there's no way to get the template ID. I think we should either a) remove the field completely or b) change it to clone from template URL. 

Also another thing, after cloning a room, the ellipses appear to be huge:
image
I remember that this was an issue last semester, it was some Safari quirk right?

**Comment by metzlr** [comment]
Nice catch. That bug is always coming back to get me. Fixed it I think. And I updated the clone section of the room settings to use a URL. It also still works if you only enter an ID.

Screen Shot 2022-05-04 at 6 33 39 PM

Also fixed a bug I noticed where new errors sometimes weren't triggering the error modal to pop up. 

Oh and I forgot to mention in my previous comment that I believe I fixed issue #65 in one of my previous commits. Obviously haven't been able to test it on a mobile device yet though.

**Comment by gmisail** [comment]
That seems to fix everything, also I can confirm that #65 is resolved. LGTM.

**Pull request merged**
